### ISSUE TITLE
CacheShardIndices returns hard bootstrap error if there are corrupt checkpoint files on disk

### ISSUE THREAD

**Issue by robskillington** [m3db/m3#1053]
FS bootstrapper does the right thing when reading data files but when it caches shard indices it will fail the whole bootstrap if there are corrupt checkpoint files because it uses `DatafileExistsAt(...)` which will return an application error instead of not found.

**Comment by richardartoul** [comment]
Discussed with @prateek , we think CacheShardIndices() should return what ranges it was able to read and which it wasn't so that the F.S bootstrapper can use that data to make shard ranges as fulfilled / unfulfilled which will enable repairs / bootstraps to succeed instead of returning an error and failing the whole thing

**Comment by richardartoul** [comment]
The impetus for this issue (corrupt checkpoint files causing bootstrap errors) has been resolved by: #1086

The CacheShardIndices returning ranges is arguably a separate issue, so I'm going to close this one and open a new one for that.
