### ISSUE TITLE
add namespace specification for prometheus remote_write / remote_read

### ISSUE THREAD

**Issue by ramazeska** [m3db/m3#1168]
Hi, i am running poc over m3db and it looks very promising
is there any plans on adding namespace support to remote_write / remote_read endpoints ?

**Comment by richardartoul** [comment]
@ramazeska The remote read/write endpoint are usually configured to write to m3coordinator, and then in the m3coordinator config you can specify which m3db namespaces to write to

**Comment by ramazeska** [comment]
Thanks, i will check it out

**Comment by ramazeska** [comment]
why there is need in separate coordinator if m3db supports direct writes from prometheus ? if this is explained in docs and i've missed it out - please point me
Thanks

**Comment by richardartoul** [comment]
You can include multiple namespaces and coordinator will dual-write / try to read from the correct namespace based on the duration of the query and the resolution of the namespaces. Example here:  https://github.com/m3db/m3/blob/master/scripts/development/m3_stack/m3coordinator.yml

You don't need one coordinator per-namespace, you can have multiple namespaces per coordinator as explained above.

M3DB as a database doesn't really support the remote read / write functionality of Prometheus directly. The reason is that the remote read/write functionality in Prometheus is kind of simple, you can only provide a URL to write to whereas M3DB requires a "smart" client that is topology aware. The way we handle this is to send writes/reads from Prometheus to M3Coordinator, then M3Coordinator has a smart M3DB client and knows how to write/read from it. If you don't want to deal with a separate service, you can technically run m3coordinator embedded in M3DB, but we don't recommend it for production workloads as its much safer to run them isolated from each other.

**Comment by ramazeska** [comment]
Thanks for you answers , it much more clearer now 
From my personal point of view - for read this fine and comfortable to use 1 coordinator, but for write i think its not the best variant ( maybe i still do not understand ) - as it implies the idea of separating data to namespaces no?
anyway - huge thanks.

**Comment by ramazeska** [comment]
I'll ask in same thread: 
i have running m3db cluster on kubernetes, i am trying to extend it by adding a physical node 
but a physical node is stuck in INITIALIZING - should i add seedNode configuration section as i am allready using external etcd cluster ?

from http://m3db.github.io/m3/how_to/cluster_hard_way/ - i've failed to understand how to set node as a storage node
please correct me if i am wrong - a seed node needed only for embedded etcd ?
