### ISSUE TITLE
m3query should use maps with equality check than pure HashFunc when intersecting series with tags

### ISSUE THREAD

**Issue by robskillington** [m3db/m3#1294]
Right now when doing binary intersections or unions with series with the same tag sets, a map of hashes calculated from each set of tags that want to be grouped together is used, using an FNV hash of the tag set for each series in question:
https://github.com/m3db/m3/blob/bbdb6c208b45b27b2ff05387c360d1020b41064a/src/query/functions/binary/and.go#L85-L102

Here you can see the FNV hash construction:
https://github.com/m3db/m3/blob/bbdb6c208b45b27b2ff05387c360d1020b41064a/src/query/models/tag.go#L154-L205

Unfortunately FNV hash collides actually quite regularly, since it's made for speed:
https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function#Non-cryptographic_hash
> As a hash designed primarily for hashtable and checksum use, FNV-1 and FNV-1a were designed to be fast to compute. However, this same speed makes finding specific hash values (collisions) by brute force faster.

The best thing is to use a compound key in a map that does an actual equality check if the hashes of two entries match.  We have a map that can be autogenerated where you can use arbitrary keys and value types (so complex compound keys, like a set of tags) and lets you specify your custom hash and equality function:
https://github.com/m3db/m3/blob/e5a271e9763c404117fa8e0f02f38be40a7d60af/src/m3ninx/index/segment/fst/postings_offsets_new_map.go#L34-L43

That would let you do a real equality check and protect against from collisions.  I highly recommend we begin using that instead of "collision possible" maps of series with their FNV value.

Here's how to autogenerate one using a generate sources makefile:
https://github.com/m3db/m3/blob/8229522ae41802db86fbb6c53b925a3a58c90552/src/m3ninx/generated-source-files.mk#L91-L103

Just something we should do when we have some time.

**Comment by arnikola** [comment]
Sounds good

Between https://github.com/m3db/m3/pull/1286 and https://github.com/m3db/m3/pull/1177 most of the work should already exist for this. I was actually a bit about leaving hash function in in 1286, and removed it from Tags so that we can

I think the next thing on my plate was https://github.com/m3db/m3/issues/1281, which is essentially adding tag matching for temporal functions, so this should be sorted between the two existing PRs and that.

**Comment by andrewmains12** [comment]
@robskillington good catch, thanks!

@arnikola is the fix for this primarily just using a genny map (which looks like it'll include equality checking)? Looks like #1286 won't necessarily solve the hash collisions on its own (even if the generated ID's are themselves unique), but switching to using genny maps might (since they do the equality check). Will you be using those in `and.go`  in #1177 ? Just trying to make sure I understand the lay of the land :).

**Comment by andrewmains12** [comment]
Cool sounds good. So long as we add the equality checks in at some point, we should be good :). Thanks for the context!
