### ISSUE TITLE
De-dupping scraped metrics

### ISSUE THREAD

**Issue by rrusso1982** [m3db/m3#1296]
I am researching the viability of using M3 in our environment and I feel like I'm missing a piece of the configuration for coordinator.

I wanted to run multiple prometheus instances that scrape the same targets for HA but only have one set of those metrics get recorded when both prometheus servers are up and online.  Does coordinator or some other component have a way to de-dup the metrics that are coming in so that I only get the one set of scrapes?

**Comment by richardartoul** [comment]
@rrusso1982 Sorry about the delay in getting back to you. Currently we recommend just having both Prom instances write to the coordinator and subsequently to M3. Since Prometheus counters are always increasing, this works out fine in practice (I.E if you get a datapoint at 12:01:00 with value 5 from Prom instances A, and then another datapoint at 12:01:01 with value 6 from Prom instance B, everything will look fine)
