### ISSUE TITLE
Clear deleted namespace data without restarting the node.

### ISSUE THREAD

**Issue by nightfury1204** [m3db/m3#1475]
Currently, If namespace is deleted, it's data does't get cleared until node is restarted. 

If replication factor is 1, then it will definitely create down time. 
If replication factor > 1, we can restart the node one by one which is troublesome if namespace gets deleted frequently.

So, it will be great if we can clear the deleted namespace data without restarting the node, without taking node down.

**Comment by prateek** [comment]
@nightfury1204 the behavior you’re describing is by design. 

A node scans and cleans up all the data for namespaces it doesn’t know about, or data past the retention period of a namespace every few minutes. Namespace additions take effect as soon as a node receives the add, but updates and removals don’t kick in until a restart. This comes from the fact that in our production workloads, we almost never remove namespaces. So we chose to require a node restart before applying the removal to avoid any data loss due to a fat finger. But this enforces the trade off you describe - where the cluster needs to be rolling restarted for the removal to take effect. 

Do you need to frequently remove namespaces in your production usage? If so, mind sharing how you’re using M3DB. It’ll help us make better tradeoffs in the future; for e.g. we could make the namespace delete apply immediately based on a config value.

**Comment by evanhuang996** [comment]
I don't delete namespaces when they are stable and suitable for the workload, but it's not always the case.After I deleting a namespace, I can't reuse the name of the deleted namespace unless nodes are restarted and data are also deleted, otherwise I think the same name will mess things up.So I prefer there is a way to delete the data without restarting the nodes.

**Comment by nightfury1204** [comment]
Our product is used by different users. We collect metrics from these products. We are planning to store these metrics in m3db. We are thinking about giving each user a separate namespace. So when user leave, we want to delete the respective namespace and clear the data from the disk(base on the policy). That's why i think it will be great if the m3db has that feature.

**Comment by martin-mao** [comment]
Hey @nightfury1204, how many users are you thinking of having? Namespaces were originally designed to keep data of the same resolution and retention in the same place - it was never the intention to have a large number of namespaces per cluster. This is because each namespace is responsible for ticking over all of it's own time series, so rather than have one of these for all your users, you end up having one per user, which will be a perf hit for you. 

If you absolutely need the data to be deleted instantly after a user leaves and you don't have a lot of users or you don't mind taking the overhead cost, then I'd say giving them their own namespace and deleting namespaces is the way to go, however, if not, I'd suggest you keep all the users data at the same retention/resolution together in the same namespace and if you need access control, implement it using metric tags on both the read and write clients. If a user leaves in this model, their data will be deleted over time (if you have 1 week retention, all of their data will be gone in a week if they no longer perform writes). 

Regardless, @prateek could we add a background job to clear the data from a deleted namespace? Or even a one off script/command? Once it's deleted I'm guessing reads and writes to the namespace are no longer possible and if it's a big namespace, it is a pain to have to rolling restart a large cluster to clear this, even though it'll clear slowly by itself.

**Comment by nightfury1204** [comment]
@martin-mao around 10k users. What kind of overhead for large number of namespaces? is it for deleting namespace?

**Comment by martin-mao** [comment]
No the overhead is just in general DB operations. For every period you set your block size to, each namespace needs to go through and rotate a new block. It does this for all the time series in that namespace, so instead of having one namespace doing this, you'll have 10K namespaces each doing this around the same time. 

Can you give me insight into whether having their data gone instantly is crucial to your use case? Because if not, you can easily achieve access control via tags on client side and the data will be gone eventually.

**Comment by prateek** [comment]
Thanks for the info all.

@evanhuang996 @martin-mao tl;dr - we have all the code in Tick doing the cleanup required already. We added a safety switch to avoid ns deletes taking effect immediately because we of paranoia. I'll make it configurable.

@nightfury1204 to echo what @martin-mao is saying, I'd strongly urge against using a namespace per user in the way you're suggesting. There's a lot of different things that would get unwieldly with 10K namespaces: there's a fixed memory overhead (haven't measure it recently so I don't have exact numbers but somewhere between 100MB-1G) per added namespace; further, each added namespace creates a lot more files, so you'll run into all sorts of performance issues we haven't seen yet. e.g. you can imagine that 10K namespaces will create a *lot* more disk seeks than 2 namespaces would so you'd be clobbering the fs cache all over the place. <plenty more if you want to get into it />

For multi-tenant workloads: I'd suggest using a "reserved tag" and doing the filtering application layer. i.e. every single metric from user `foo` has the following tag added to it `__appscode_userid:foo`. You'd handle this in the ingest path, and every time they query, you'd also add the equivalent restriction. We've done this in our production workloads with many thousands of users to great success.

**Comment by nightfury1204** [comment]
@prateek thanks for the response. I have read http://m3db.github.io/m3/operational_guide/namespace_configuration/. In here, for modifying the namespace it use the not deleting namespace without node restart feature. So, you might wanna keep this in mind. I think you already know it, just mentioning it for safety measure.

**Comment by whc9527** [comment]
Prometheus collects the host data in the AWS scaling group and writes it to M3DB. How to delete the EC2 Metric data of a non-existent EC from M3DB？ thx!!!
