### ISSUE TITLE
Arithmetic binary operators between two vectors return empty result on m3's promql engine

### ISSUE THREAD

**Issue by jhaohai** [m3db/m3#1520]
We are using embedded m3coordinator as prometheus datasource on grafana.
query:
```
node_memory_MemTotal{instance=~"$node"} - node_memory_MemAvailable{instance=~"$node"}
```
return the memory used for each node on original prometheus instance.
But it returns empty result on m3db.
We are using 0.8.0 and using the example config file from the repository with only customize on etcd and namespaces fields.

**Comment by jhaohai** [comment]
I put a prometheus in front of m3 and everyhing works fine now.
So it seems m3db's promql engine is fully implemented as the original prometheus.

**Comment by martin-mao** [comment]
Our promql engine has most of the prometheus functionality implemented. @benraskin92 @arnikola Can you guys have a look here?

**Comment by arnikola** [comment]
This should be fixed by 1604; issue was that we were not ignoring tag names in comparisons. We're putting out a release today (0.8.5) that should solve this problem

There's a workaround if you're not able to update; `node_memory_MemTotal{instance=~"$node"} - ignoring(__name__) node_memory_MemAvailable{instance=~"$node"}` will copy this functionality.

**Comment by arnikola** [comment]
Let me know if this solves your issue :)
