### ISSUE TITLE
Set/update namespace schema in etcd

### ISSUE THREAD

**Issue by Haijuncao** [m3db/m3#1614]
As part of adding complex type support and m3db schema management to m3db (dbnode), we needed to provide tooling to allow service developer to update user defined schema for their namespace as part of the namespace metadata.

There are two ways to update namespace metadata (stored in etcd) at the moment:
1. m3coordinator restful api: a gateway that is mostly built to expose prometheus/grafana proxy endpoint on query path, in addition, it also exposed namespace metadata management api. It currently colocates with m3 query deployment.
2. m3admin (a cli tool used by m3 admin)

We will propose 3 phases to tackle the issue

1. immediate: in order to unblock #1578, we need still load schema from dbnode config (and load it into schema registry)
2. short term: create a namespace metadata management library (CRUD operation) that can be shared by both m3admin and m3coordinator (so move up the abstraction from kv.Store). 
3. long term: a standalone m3db metadata management service that exposes CRUD restful api for the purpose control plane/self service integration.  The m3db coordinator (similar to a cassandra coordinator) should be used to receive routing topology update and proxy read/write requests between application and dbnode, i.e. it is a proxy on the data plane.

**Comment by richardartoul** [comment]
Looks good to me. The only thing I'd mention regarding #3 is that I think it would be good to reuse m3coordinator as much as possible so we don't have to reimplement a bunch of stuff. Especially since we can embed it in the dbnodes so we could make it so you could administer the cluster from any of the regular m3db nodes. I.E it might be worth trying to evolve m3coordinator as opposed to building a new service

**Comment by Haijuncao** [comment]
#3 still implies reuse, which comes from #2

The intention is to separate metadata management from request proxy.

However, we may still want to colocate coordinator with meta mgmt in one service/deployment just to reduce operation complexity.

**Comment by robskillington** [comment]
Hm, yeah we have been mainly putting all administration in coordinator endpoints since the idea is to both have dedicated coordinators, but also expose local coordinator endpoints that solely operate on the local clusters topology. (i.e. always sets the zone, environment, other vars if talking to coordinator endpoints on the local dbnode)

I guess what I'm getting at is that it should be fine to have administrative endpoints solely available from coordinator, since coordinator is local to dbnodes even in deployments that have dedicated coordinators.

**Comment by Haijuncao** [comment]
> Hm, yeah we have been mainly putting all administration in coordinator endpoints since the idea is to both have dedicated coordinators, but also expose local coordinator endpoints that solely operate on the local clusters topology. (i.e. always sets the zone, environment, other vars if talking to coordinator endpoints on the local dbnode)
> 
> I guess what I'm getting at is that it should be fine to have administrative endpoints solely available from coordinator, since coordinator is local to dbnodes even in deployments that have dedicated coordinators.

sounds good.

**Comment by Haijuncao** [comment]
schema update endpoint is added to m3query/coordinator via #1643
