### ISSUE TITLE
Two-region deployment with RF=3 ?

### ISSUE THREAD

**Issue by filippog** [m3db/m3#1708]
Hi all,
I'm in the process of evaluating M3, we have two datacenters and would like to deploy M3 across those though with RF=3, from reading the documentation on topology/placements it isn't clear to me whether that's a supported configuration? And if so how `isolationGroup` would look like to achieve region and rack/row awareness.

thanks!
Filippo

**Comment by martin-mao** [comment]
Hey @filippog,

I'd probably recommend having two clusters, one in each datacenter with the isolation group being the rack of the machine rather than spreading across both datacenters. The reason is that when you spread across both, for a single particular shard, one DC (let's call it DC1) will have two replicas and the other DC (DC 2) will have one replica. Now, if you lost DC1, you only have 1 out of 3 replicas, which will mean you've lost quorum in your cluster and you will no longer be able to successfully serve reads or writes.

We only recommend one replica per zone or DC when you have three of them. In your case, I'd suggest having one cluster in each DC with all the metrics from one DC being stored my the M3 cluster in that DC. You can then configure our query nodes query across them so you can join data from both DCs.

I hope that makes sense - let us know what you end up doing!

**Comment by chr0mag** [comment]
> ...You can then configure our query nodes query across them so you can join data from both DCs.

@martin-mao - Is there some example YAML you can point us to that shows how to configure this cross region/DC query capability? I'm aware of these example configs:

- https://m3db.github.io/m3/query_engine/config/annotated_config/
- https://github.com/m3db/m3/tree/master/src/query/config

...as well as the default that comes with the `quay.io/m3db/m3dbnode` Docker image but its not clear to me how to make one m3Coordinator/query instance aware of the other clusters (or m3Coordinator/query instances) ?

**Comment by martin-mao** [comment]
@chr0mag The best example is probably inside here: https://github.com/m3db/m3/tree/master/scripts/docker-integration-tests/query_fanout where you can see configs for three different region/DCs. Feel free to drop a note in our Slack channel if you have more questions about this - and also, a revamp of the docs is coming soon, so there'll be better documented examples.

**Comment by chr0mag** [comment]
@martin-mao - that was helpful. Thanks.

> and also, a revamp of the docs is coming soon, so there'll be better documented examples.

Definitely looking forward to update docs.
