### ISSUE TITLE
Prometheus HA setup

### ISSUE THREAD

**Issue by nextus** [m3db/m3#1972]
Hi and thank you for that project!
I'm playing around with it a little bit and have few questions about Prometheus HA setup in M3 stack.
- Does M3db support some kind of [thanos-like](https://thanos.io/getting-started.md/#deduplicating-data-from-prometheus-ha-pairs) deduplication?
- How to install the «aggregation tier» that you have mentioned in your [docs](https://m3db.github.io/m3/how_to/query/)? That is, is there any way to offload downsampling from the m3coordinator to some kind of aggregation service which is possible to scale horizontally?

**Comment by martin-mao** [comment]
Hey @nextus,

Generally, once you have M3 up and running, you don't need Prometheus HA since all writes will be available in M3 relatively quickly - our queries don't stitch data from Prom and M3 together, all reads come directly from M3 which is highly available. In most cases, having a single instance will suffice, as you resume scraping after a restart etc and all scraped values will be stored with three replicas in M3.

If you are really worried about availability of your Prom instance (of course, if it's down for extended periods, it cannot forward writes to M3), you can just have two instances both writes to M3. If they happen to scrape on the same cycle and have the same timestamps, then those writes will be de-duplicated inside our DB and if they have different time stamps, then it would the same as if one instance scraped twice - we will record both values. When you query and apply rate functions, you won't notice the extra data. This does require more storage overall of course, but that's the price to pay if you absolutely need two Prom instances up for scraping purposes. 

Yes, the aggregation tier is the horizontally scalable and highly available for aggregation. Our docs are not great here - the best way to get started is probably by joining our aggregator slack channel. Shoot me your email and I'll add you.

Cheers,
Martin

**Comment by nextus** [comment]
Thanks for the reply. I will contact you soon, I think.
