### ISSUE TITLE
M3DB backup and amount of data points supported/tested

### ISSUE THREAD

**Issue by jgrossmac** [m3db/m3#2043]
We are looking to use a timeseries DB and came across M3DB.  One of our requirements is to ensure there is a proper backup/restore strategy once deployed on Kubernetes as we will likely eventually have billions or trillions of time series data points.  This leads me to two questions:

1. Has M3DB been tested in Kubernetes with this many data points?
2. What is the recommended best practice to backup and restore data on an M3DB cluster on Kubernetes?

Thank you!

**Comment by schallert** [comment]
Hey @jgrossmac, sorry this got buried in the inbox.

Re: 1, I can confirm that M3DB has been successfully deployed on Kubernetes storing billions of unique time series. For most use cases the fact that it's running on Kubernetes shouldn't be too different than not, assuming you're comfortable operating Kubernetes and ideally have capacity to put M3DB on dedicated (tainted) nodes. I'd recommend at the minimum using your cloud provider's SSD-backed remote block storage. If you have operational experience with local SSDs and Kubernetes local volumes they can also help with performance.

Re: 2, M3DB backup and restores are currently an open-ended issue in the community. There's efforts underway to create a tool to dump M3DB data to object store and I'd encourage you to join our monthly community meeting to hear more about those efforts. In the interim, if using remote block store than disk snapshots can possibly suffice. Admittedly in most of our production experience with M3DB we depended on the failure domain-aware replication of data for durability, and hadn't run into a situation where we lost historical data because of failures.

I'd be happy to chat more about any of these topics. If you're not already in it, I'd encourage you to join our [Slack] instance where we're pretty active. Feel free to ping me there directly as well.

[Slack]: http://bit.ly/m3slack
