### ISSUE TITLE
docs for local persistent volume when deploying m3 on k8s.

### ISSUE THREAD

**Issue by yuswift** [m3db/m3#2081]
## General Issues
According to the post(https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/), uber used local pv when deploying m3 on k8s. However, when I read docs on https://m3db.github.io/m3/how_to/kubernetes/ ，I can not find reference about local persistent volume as the replacement of remote storage. Is there any docs about local persistent volume with m3?

**Comment by xmcqueen** [comment]
I found a few more docs for this situation and got it going.  I'll put out a PR for updating the docs.  Here are some notes for you:

[https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/getting-started.md](kubernetes-sigs)

Make sure the local fs has the storage attached and is ready. (like /data/m3db or whatever)
Create a storage class that will represent your local storage like:

`
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
`

Setup the StatefulSet to use a dataDirVolumeClaimTemplate (note its using the above-created storage class "local-storage"):

`
  isolationGroups:
  - name: group1
    numInstances: 1
    storageClassName: local-storage
.
.
.
  dataDirVolumeClaimTemplate:
    metadata:
      name: m3db-data
    spec:
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
        limits:
          storage: 10Gi
      persistentVolumeReclaimPolicy: Retain
      storageClassName: local-storage
      local:
        path: /data/m3db
      nodeAffinity:
        required:
          nodeSelectorTerms:
          #regular k8s-style selector for the nodes that will have the local storage
          #you'll have to label the nodes in this case
         #they would be labelled "company.com/m3db: node"
          - matchExpressions:
            - key: company.com/m3db
              operator: In
              values:
              - node
`
Deploy that and you'll see the pods begin to start and go into pending.  Each will create a pvc, and go into pending because there are no pv's yet. You can likely create all the pv's first and have no problems, but I had a problem, so I created the pv's on-demand, as-needed and the problem went away. NOTE: each host has its own pv.  (Find a better way to do this. There must be a template kind of thing for this too.)  See the below pv-1 which has a hostname in it.  I also have pv-2, with a second hostname in it, etc.  

So create the required pv's and the pods will start:

`
apiVersion: v1
kind: PersistentVolume
metadata:
  name: m3db-pv1
spec:
  capacity:
    storage: 100Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/m3db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - server1.company.com
`

Create this PV, and you'll see the pod will get scheduled to run on the host named server1.company.com.

**Comment by yuswift** [comment]
> I found a few more docs for this situation and got it going. Here are some notes for you:
> 
> [https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/getting-started.md](kubernetes-sigs)
> 
> Make sure the local fs has the storage attached and is ready. (like /data/m3db or whatever)
> Create a storage class that will represent your local storage like:
> 
> ```
> apiVersion: storage.k8s.io/v1
> kind: StorageClass
> metadata:
>   name: local-storage
> provisioner: kubernetes.io/no-provisioner
> volumeBindingMode: WaitForFirstConsumer
> ```
> 
> Setup the StatefulSet to use a dataDirVolumeClaimTemplate (note its using the above-created storage class "local-storage"):
> 
> ```
>   isolationGroups:
>   - name: group1
>     numInstances: 1
>     storageClassName: local-storage
> .
> .
> .
>   dataDirVolumeClaimTemplate:
>     metadata:
>       name: m3db-data
>     spec:
>       volumeMode: Filesystem
>       accessModes:
>         - ReadWriteOnce
>       resources:
>         requests:
>           storage: 10Gi
>         limits:
>           storage: 10Gi
>       persistentVolumeReclaimPolicy: Retain
>       storageClassName: local-storage
>       local:
>         path: /data/m3db
>       nodeAffinity:
>         required:
>           nodeSelectorTerms:
>           #regular k8s-style selector for the nodes that will have the local storage
>           #you'll have to label the nodes in this case
>           #they would be labelled "company.com/m3db: node"
>           - matchExpressions:
>             - key: company.com/m3db
>               operator: In
>               values:
>               - node
> ```
> 
> Deploy that and you'll see the pods begin to start and go into pending. Each will create a pvc, and go into pending because there are no pv's yet. You can likely create all the pv's first and have no problems, but I had a problem, so I created the pv's on-demand, as-needed and the problem went away. NOTE: each host has its own pv. (Find a better way to do this. There must be a template kind of thing for this too.) See the below pv-1 which has a hostname in it. I also have pv-2, with a second hostname in it, etc.
> 
> So create the required pv's and the pods will start (create a m3db-pv2 for server2 etc.):
> 
> ```
> apiVersion: v1
> kind: PersistentVolume
> metadata:
>   name: m3db-pv1
> spec:
>   capacity:
>     storage: 100Gi
>   # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
>   volumeMode: Filesystem
>   accessModes:
>   - ReadWriteOnce
>   persistentVolumeReclaimPolicy: Retain
>   storageClassName: local-storage
>   local:
>     path: /data/m3db
>   nodeAffinity:
>     required:
>       nodeSelectorTerms:
>       - matchExpressions:
>         - key: kubernetes.io/hostname
>           operator: In
>           values:
>           - server1.company.com
> ```
> 
> Create this PV, and you'll see the pod will get scheduled to run on the host named server1.company.com.
> 
> NOTE: I used the m3db-operator and I also recommend using it.

thanks a lot!
