### ISSUE TITLE
Pod readiness script does not check placement correctly

### ISSUE THREAD

**Issue by transacid** [m3db/m3#2113]
The script which checks the dbnode pod readiness (/bin/m3dbnode_bootstrapped.sh) does not correctly check the placement. The command used to check the placement (here the variables are already substituted and some parameters dropped for readability) is:
```
curl http://localhost:7201/api/v1/placement | jq -e '.placement.instances | .["m3db-cluster-rep0-0"]'
```
this will always fail since the resulting json looks different (at least in our case) here's an excerpt:
```
curl -s http://localhost:7201/api/v1/placement | jq -e '.placement.instances' | head -10
{
  "{\"name\":\"m3db-cluster-rep0-0\"}": {
    "id": "{\"name\":\"m3db-cluster-rep0-0\"}",
    "isolationGroup": "europe-west1-b",
    "zone": "embedded",
    "weight": 100,
    "endpoint": "m3db-cluster-rep0-0.m3dbnode-m3db-cluster:9000",
    "shards": [
      {
        "id": 1,
```
like described here https://www.m3db.io/openapi/#tag/M3DB-Placement you match against the "property" which in our case is `{\"name\":\"m3db-cluster-rep0-0\"}`
since the readiness script always returns `Host not present in topology` (which is not true) we are having a hard time upgrading the underlying kubernetes cluster because one node after another get upgraded even though nodes are still bootstrapping.

**Comment by robskillington** [comment]
Hey @transacid this was an issue that occurred with the operator pre-0.3.0. 

We switched to using the bootstrap endpoints directly instead of the health script which was not a sustainable solution for our readiness/health probes.

Here's the fix in question:
https://github.com/m3db/m3db-operator/pull/135/files#diff-b27159881d90b11cdce532fb8e9a13aa

Here's the release notes for 0.3.0 mentioning this:
https://github.com/m3db/m3db-operator/releases/tag/v0.3.0
