### ISSUE TITLE
New CI gating for m3 pipelines

### ISSUE THREAD

**Issue by KevinGrandon** [m3db/m3#2157]
Hello, we are implementing new mandatory CI gating for all Buildkite pipelines. This would involve enabling the following pipeline in Buildkite and decommissioning the current CI gate.

<img width="707" alt="image" src="https://user-images.githubusercontent.com/122602/74857804-13c17000-52f9-11ea-99c8-50a9e1601a86.png">

As part of this we can enable the Buildkite job to be public as well, so third party contributors can see build pages.

We can also update CI gate to work with labels, having it respond to the label event, and unblock the Buildkite job if that would be beneficial. See: [unblock job API](https://buildkite.com/docs/apis/rest-api/jobs#unblock-a-job)

Our automated enforcement saw that was disabled, so filing this issue so we can discuss further.

**Comment by KevinGrandon** [comment]
FYI - I've enabled the Buildkite gating again, as well as made build pages public so all third party contributors can read build pages. Let me know what you think of this approach. @robskillington @schallert 

Next up we can add a bot to automatically unblock the build when the CI tag is added if you would like.

**Comment by schallert** [comment]
Hey @KevinGrandon, thanks for the update. I didn't realize this was intentional and the other day commented out that BK step in favor of ci-gate.

We'd prefer the approach you mentioned where ci-gate calls the Buildkite unblock API based on what it reads from the GitHub API. We have trusted M3 contributors with write access to the GH repo, or that we may whitelist in ci-gate, but we probably can't add them to the BK org. For these cases having CI permissions based on GitHub and not Buildkite is really helpful.

I have one concern about making the pipelines public in their current state without 1 change first. Would you mind making them private temporarily until we can chat 1:1? Feel free to join the [M3 OSS Slack](http://bit.ly/m3slack) and ping me there, or our [Gitter](https://gitter.im/m3db/Lobby).

**Comment by KevinGrandon** [comment]
@schallert Sure thing. I'll join your slack and we can chat there.

**Comment by KevinGrandon** [comment]
Let's follow-up over slack or e-mail anytime keving (at) uber. Closing for now.

**Comment by robskillington** [comment]
Thanks a lot @KevinGrandon - public build logs makes sense, hopefully we can clear up any existing issues with that and get that going.
