### ISSUE TITLE
Can m3dbnode expand many machines at the same time?

### ISSUE THREAD

**Issue by Constlin** [m3db/m3#3118]
Hello, M3 team. First, thanks for the greate works. And I have a question about the dbnode's dynamically expand machines.

Can M3 expand many machines at the same time? I found that m3 only can expand machine one by one,  it make a result that the data will repeat migration and it will be very slow if we have a lot of machines need to add into the cluster.

By the way, I use the curl to expand machine:
curl -X POST coordinator:7201/api/v1/services/m3db/placement -v -d '{
  "instances": [
    {
      "id": "a",
      ...........
    },
    {
       "id": "b",
      ...........
    },
    ......
  ]
}'

But it seems that dbnode will just expand the first machine, is there any way to dynamically expand many machines at the same time?

**Comment by gibbscullen** [comment]
@Constlin -- looking into this.

**Comment by gibbscullen** [comment]
Summarizing thread in Slack discussing this issue: 
- updating the cluster placement with the desired final should work for this (but not possible with the operator)
- PlacementAddRequest takes a list of candidates: https://github.com/m3db/m3/blob/master/src/query/generated/proto/admin/placement.proto#L19; and they can add all eligible ones here: https://github.com/m3db/m3/blob/master/src/query/api/v1/handler/placement/add.go/#L135-L138
- The placement algorithm adds the nodes serially, but that's just an internal implementation detail, and only the final placement that is returned by the algorithm is used by the nodes to determine where shards should be moved to. For example, let's suppose in your initial placement shard X is assigned to node A and you then add two nodes to the placement in a single request. If the first node being added creates a placement where shard X is assigned to node B and then the second node being added creates a placement where shard X is assigned to node C then since only that final placement is returned by the algorithm shard X will stream directly from node A to node C. The fact that it was assigned to node B in an intermediate placement is completely transparent.
-  The instance selector won't add all instances in the requests unless the AddAllCandidates option is enabled and it doesn't appear that there's a way to do that; So until it does you would need to use placement set API
