### ISSUE TITLE
Use a lockfile in filePathPrefix

### ISSUE THREAD

**Issue by prateek** [m3db/m3#641]
Already experienced configurations when multiple processes point to the same directory. Should catch this using a lockfile.

**Comment by richardartoul** [comment]
Lets make sure we choose an implementation that automatically releases the lock if the process dies or the host restarts so we don't add an additional manual task that needs to be performed to recover from an abrupt failure.

**Comment by edkolev** [comment]
I'll try to implement this, please assign to me.

Regarding the implementation, seems like we can't rely on automatic cleanup (due to hard restart, OOM killer, etc). Maybe the lock file could contain the pid of the process. Then, when we try to create a lock file, we'll ignore an existing lock file if it contains a dead PID (checking if a process is alive might be tricky though - maybe sending signal `0` could do it). Does something like this sound like a good approach?

**Comment by richardartoul** [comment]
The PID solution seems brittle to me, especially since they get recycled and such. I did a little investigation and it seems like the ideal solution is to use the [fcntl system call](http://man7.org/linux/man-pages/man2/fcntl.2.html) - specifically see the "Advisory record locking" and "Open file description locks" sections. Specifically it says:

```
 As well as being removed by an explicit F_UNLCK, record locks are automatically released when the process terminates.
```

[This document](https://gavv.github.io/blog/file-locks/) also has a good summary.

It looks like these locks are automatically released when a process dies, and they're also allocated in memory so you should always end up in a clean state when a machine reboots.

**Comment by richardartoul** [comment]
@edkolev 

Sure. I think this is a fairly re-usable thing that we may want for multiple services, so maybe we can put it in a shared location. Right now I'm thinking here would be good: https://github.com/m3db/m3/tree/master/src/x

Make it a standalone package / function so that we can use it in different places, and then in a separate P.R we can add it to M3DB.

**Comment by edkolev** [comment]
Hey, Richard, I now see that I've provided wrong information in my comment above - the lock *file* is never removed automatically (when the process exits or is killed). Instead, just the *lock* on that file is removed. This makes sense because only the lock resides in the memory, not the file itself.

**Comment by richardartoul** [comment]
@edkolev That seems like a reasonable solution to me right? It doesn't really matter whether the file is cleaned up or not as long as there is only ever one.

**Comment by edkolev** [comment]
@richardartoul Correct, it should do the job - only one process will be able to hold a lock, and cleaning up locks will be optional.

**Comment by richardartoul** [comment]
Now that #1225 is landed, the next step is to integrate it with M3DB (probably in `src/dbnode/server.go`)
