### ISSUE TITLE
More information needed

### ISSUE THREAD

**Issue by jilongs** [m3db/m3#775]
Hi,

It's great to see another time series database written in Go other than InfluxDB. As I'm looking for a good solution for our time series data, I think m3db might be a strong candidate.

Can you please share more information about this project, like the roadmap and benchmark compared to InfluxDB? That would be very helpful.

Thanks for all your efforts.

**Comment by robskillington** [comment]
Hey, thanks for the query.  We'd be interested to hear about what your use case is.  As it stands we're primarily aimed at instrumentation use cases, e.g. metrics and monitoring right now.  

We haven't ruled out making it more generally accessible and easy to use as a general TSDB but for right now it's definitely not optimized or easy to use for that use case (all current interfaces require a float64 as the value for instance to write a time series value).

What kind of time series data are you considering storing?

**Comment by jilongs** [comment]
Thanks for your reply, what we want to store is IOT information, and float64 should be fine for our use case I think.

**Comment by justinjc** [comment]
@jilongs - I'm trying to understand your use case a little more. Would you only be interested in storing real time data or would you also store historical and/or futuristic data? Also, would you want to migrate existing data you already store somewhere else to M3?

**Comment by prateek** [comment]
@jilongs cheers, yeah that doesn’t sound like much load at all. Few different things to point out:

- Justin’s working on supporting arbitrary write times. But even without that, m3db (as in the code in master) supports a configurable look back and look ahead period during which writes are accepted. I don’t recommend setting that to very large values but If you’re guaranteed all your data shows up within say 2-24h of creation, you could definitely use m3db today. Let us know if you wanna try that and we can give you more specific pointers for how to get the ball rolling. 
- Grafana integration: so m3db exposes a datamodel for each timeseries to have a single unique ID and a collection of tag pairs using which the ID can be retrieved. Internally we use it to store Prometheus/Graphite/M3 metrics in the same deployment. All of this to say, it’s agnostic to query language. The query engine that’s in this repo today is still in development but it’ll support PromQL soon. Using that you’d be able to wire up Grafana to query your metrics in M3db using PromQL. 

While I don’t know all the specifics of your workload, I feel confident saying for the scale you’re talking about, you shouldn’t have load issues with a 3 host cluster. Happy to help you get an e2e setup going if you wanna put it through the paces with your real workload.

**Comment by genericgithubuser** [comment]
Hi @prateek , I don't mean to hijack this thread, but you mention you are storing graphite metrics in m3db along with your prometheus data.  I am trying to replace our internal graphite deployment. I just got through doing a test deploy of influx, but would love to be able to use m3 instead since it's open source, go based, and can be clustered.  
So to clarify:
What's the best way to push data into m3db when not using prometheus?  Currently clients leverage mostly collectd or diamond agents to get their system metrics in, and then various simple scripted methods to get app data in.  Is there existing code/clients that might already be doing this, or would I need to write my own client that talks to either the store api or the prom remote write endpoint or something?  As you know, one positive for graphite is that it's simple for customers to integrate with it.  Influx integration is easy as well, so I'm hoping to have an easy path for customers to start utilizing m3.
