### ISSUE TITLE
About M3DB in production

### ISSUE THREAD

**Issue by huydx** [m3db/m3#786]
Hi m3db team, thanks for the great work!

We're considering use m3db for our internal monitoring platform. We have some question regard m3db stability:
- How is it scale at UBER now and how stable is it?
- Could you share UBER internal cluster statistic (how many nodes serving how many metrics), and the spec of each node if the information is available?
- Is the inverted index implementation stable yet?
- I see a lot of undocumented modules like m3cluster, m3ctl, are those modules optional or mandatory? Or just m3dbnode / m3coodirnator are only 2 mandatory components?

**Comment by robskillington** [comment]
Hi @huydx - thanks for the inquiry.

Here's some answers, I can't share numbers that represent all our machines but I can mention numbers about individual clusters.

1. With respect to the scale, again while I can't give numbers representing all our machines, I can say that as an example we have one cluster at Uber that performs 8.85 million writes/sec with 130 nodes at replication factor 3.  Each node performs about 200k writes/sec very comfortably, with regular peaks of 350k writes/sec.  We've also run the same machines at 1.5x that with less comfort, with regular peaks of 700k writes/sec.  Overall we're pretty happy about the efficiency, but we would like to continue to push the performance of course though to drive costs even further down over time.  During benchmarks we've been able to reach considerably higher numbers, but again we don't want to run at that level of stress in production until we have tuned it further, there's some low hanging fruit here but we'd prefer to spend time on other things right now. 

Here you can see the standard work load on one of our clusters:

![screen shot 2018-07-11 at 11 22 47 am](https://user-images.githubusercontent.com/339615/42582305-c6afed9e-84fc-11e8-9ac2-94dbdf4c0808.png)

2. I shared the writes/sec and number of machines for a single cluster above, although the caveat is that we're not using the inverted index on those clusters just yet.  From our testing of the inverted index on our test clusters, which are only 20 nodes or so, we're seeing roughly 10-20% lower performance but with about 20-30% larger heap sizes.  In terms of the machine specs, the machines we're using for this workload are 32 core Xeons roughly 2ghz each with 256gb memory and a 1TB SSD.  Go is using about 54gb of memory, and there's mmap'd disk files using memory that could be evicted by the OS if required on top of that.

3. The inverted index is stable on the write path but we don't believe the read queries are performant enough for people to use it in production (we have it turned on and nodes are steady at similar write workloads as our non-inverted index enabled clusters).  The read performance of the index is our current focus, and we are onboarding an internal cluster that takes production traffic too so we need to raise the bar on QPS.  We estimate two weeks left before we are in a place where we're using it production actively and happy with the read performance.

4. m3dbnode and m3coordinator are the only two required components to run, all the other repositories are more library based, with the exception of the m3aggregator.  Eventually all libraries and services will be built out from the single repository (we are moving from decentralized repos to single repo).  You may want to think about running the m3aggregator however if you begin to use the end to end stack more, it's useful because if you start downsampling at 1min or 10min you ideally don't want to lose downsampled tiles when you restart the m3coordinator and have partial 10min tiles.  m3aggregator is replicated and allows you to downsample metrics reliably during metrics ingestion.

**Comment by huydx** [comment]
Hi @robskillington , many thanks for your detail answer. I got almost everything I want to know, and one more last question:
- Without inverted index, m3db still able to search by tag and prometheus read/write plugin still works?

**Comment by robskillington** [comment]
Hey @huydx - no problems.

Re: your last query, the search feature and prometheus read/write feature is indeed functional (covered by our integration tests too).  However we have seen that you can't perform that many queries involved the inverted index per second without starting to time out further queries.  A few queries per second is currently at all it can take.  Our production instances take thousands of queries per second, so we need to rectify this before we can use it ourselves.

So it's stable in that it doesn't crash, it just uses a lot of resources than normal when issuing more than a few queries per second, so we're rectifying that this and next week.

**Comment by DocEmmetBrown** [comment]
Hey @robskillington , 
Thanks for the infos you shared about cluster size, it's very insightful !
Now that you have 6 more month running these clusters, probably using inverted index ( I guess :) ), would you have updated numbers and best-practices on the sizing of M3DB clusters ?
Thanks

**Comment by richardartoul** [comment]
@DocEmmetBrown Sorry for the delayed response. Its hard to give advice without some concrete numbers (admittedly we do need to write a sizing guide). If you join our [Gitter channel](https://gitter.im/m3db/Lobby) I'm sure we can help you out in more detail there.

**Comment by richardartoul** [comment]
Closing this as a stale discussion

**Comment by 2317006619** [comment]
Hi m3db team, thanks for the great work!
I'm learning about m3db, and use it first time. I have some questions about m3db cluster.  I create a cluster of 3 seedNodes. They worked good at begain, but after I restart one node by[systemctl restart m3dbnode], I found error logs, like that, how can I resolve this promblem?
(I'm not good at English, So may be the conten is not very easy for understanding .)

`Jul 21 09:59:12 controller1 m3dbnode[2716632]: {"level":"info","ts":1595296752.1378393,"msg":"bootstrap finished","namespace":"default","duration":4.278348942}
Jul 21 09:59:12 controller1 m3dbnode[2716632]: {"level":"info","ts":1595296752.137905,"msg":"bootstrapped"}
Jul 21 09:59:13 controller1 m3dbnode[2716632]: failed to reach the peerURL(http://172.27.147.203:2380) of member d15050ccb5b052bc (Get http://172.27.147.203:2380/version: dial tcp 172.27.147.203:2380: connect: connection refused)
Jul 21 09:59:13 controller1 m3dbnode[2716632]: cannot get the version of member d15050ccb5b052bc (Get http://172.27.147.203:2380/version: dial tcp 172.27.147.203:2380: connect: connection refused)
Jul 21 09:59:13 controller1 m3dbnode[2716632]: {"level":"info","ts":1595296753.7712364,"msg":"successfully updated topology","numHosts":3}
Jul 21 09:59:15 controller1 m3dbnode[2716632]: health check for peer d15050ccb5b052bc could not connect: dial tcp 172.27.147.203:2380: connect: connection refused
Jul 21 09:59:17 controller1 m3dbnode[2716632]: failed to reach the peerURL(http://172.27.147.203:2380) of member d15050ccb5b052bc (Get http://172.27.147.203:2380/version: dial tcp 172.27.147.203:2380: connect: connection refused)
Jul 21 09:59:17 controller1 m3dbnode[2716632]: cannot get the version of member d15050ccb5b052bc (Get http://172.27.147.203:2380/version: dial tcp 172.27.147.203:2380: connect: connection refused)
Jul 21 09:59:20 controller1 m3dbnode[2716632]: health check for peer d15050ccb5b052bc could not connect: dial tcp 172.27.147.203:2380: connect: connection refused
Jul 21 09:59:21 controller1 m3dbnode[2716632]: failed to dial d15050ccb5b052bc on stream Message (peer d15050ccb5b052bc failed to find local node 2228492727175640)
`
