### ISSUE TITLE
Commit Log Write Performance Improvements

### ISSUE THREAD

**Issue by prateek** [m3db/m3#947]
We have talked about performance improvements for the commit log a few times, going to start tracking the different experiments/ideas in this ticket. 

--------------------------
- **Idea**: batched write APIs https://github.com/m3db/m3/issues/458 

--------------------------
- **Experiment**: Rolled out a version of the commit log code which does not make any writes to the disk, but does everything else for commit log processing (https://github.com/m3db/m3/pull/944) to a single production host. Here's what it looked like v another host. The host with the /dev/null build is in green. 
With the caveat this is a rudimentary experiment, we still do observe high spikes in the commit log queue size.

![screen shot 2018-09-25 at 20 45 55](https://user-images.githubusercontent.com/199982/46051208-0ef98c00-c106-11e8-9bd6-8e4ac746eaa9.png)

/cc @richardartoul @robskillington

**Comment by richardartoul** [comment]
@prateek I'm glad that the experiment showed it wasn't a disk issue. I have a few potential fixes I'm gonna test out today and then document the results.

**Comment by richardartoul** [comment]
I feel like this ticket was mostly addressed by #1157 and #1160

The one last thing I'd like to do is making it so that when you open a new commitlog file, it actually just lets you immediately start using one thats already ready and then it asynchronously creates a new one so that file creation doesn't block the queue for any amount of time during rotation

**Comment by richardartoul** [comment]
All of these tasks have been completed
