### ISSUE TITLE
Fix double metric allocation in m3agg

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#992]
m3agg allocates a metric called "writes.error" more than one time which causes it to panic when Prometheus metrics are enabled.

Once this is fixed, we can re-enable m3agg metrics when it is embedded inside of m3coordinator.

**Comment by robskillington** [comment]
Interesting... the tally scope should prevent this from happening since it will de-dupe any metrics that are registered.  However if something like coordinator also registers that with a different/unique `tally.Scope` then this issue can arise.

In our config we could set `onError: log` or `onError: stderr` or something, although this will drop metrics that actually can't be registered silently.

**Comment by richardartoul** [comment]
It was pretty late so it’s possible I misread something, but I’m pretty sure I traced through the code carefully and coordinator doesn’t allocate the metric in question so my guess is (somehow) it’s happening twice in m3agg
